// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9jA4lkL-WJiPtlLBC1Dl-_RFrppJUY6s',
    appId: '1:37803276260:web:d10178de6a185e29cef9f1',
    messagingSenderId: '37803276260',
    projectId: 'warzero-6fe4d',
    authDomain: 'warzero-6fe4d.firebaseapp.com',
    storageBucket: 'warzero-6fe4d.firebasestorage.app',
    measurementId: 'G-RR3HP1P8GJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpPjctiAsaHJ_6UJxXZO8R8Ch9sqWvLag',
    appId: '1:37803276260:android:a1ebfcdf62a3af20cef9f1',
    messagingSenderId: '37803276260',
    projectId: 'warzero-6fe4d',
    storageBucket: 'warzero-6fe4d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKSj6ElxygDchYKeN4dQ7a4EZ5SnR93q0',
    appId: '1:37803276260:ios:dfbac60fa2ff483fcef9f1',
    messagingSenderId: '37803276260',
    projectId: 'warzero-6fe4d',
    storageBucket: 'warzero-6fe4d.firebasestorage.app',
    iosBundleId: 'com.example.warzero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKSj6ElxygDchYKeN4dQ7a4EZ5SnR93q0',
    appId: '1:37803276260:ios:dfbac60fa2ff483fcef9f1',
    messagingSenderId: '37803276260',
    projectId: 'warzero-6fe4d',
    storageBucket: 'warzero-6fe4d.firebasestorage.app',
    iosBundleId: 'com.example.warzero',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9jA4lkL-WJiPtlLBC1Dl-_RFrppJUY6s',
    appId: '1:37803276260:web:8d93a77cf1859bd1cef9f1',
    messagingSenderId: '37803276260',
    projectId: 'warzero-6fe4d',
    authDomain: 'warzero-6fe4d.firebaseapp.com',
    storageBucket: 'warzero-6fe4d.firebasestorage.app',
    measurementId: 'G-CGSCQZ0Q0S',
  );
}
